### ISSUE TITLE
Does this work on the client as well?

### ISSUE THREAD

**Issue by srnyx** [wafflecoffee/clean-logs#2]
Like will it remove things from the log files?

**Comment by wafflecoffee** [comment]
I've only been testing it on the client, so I sure hope it works on the client :smile:

**Comment by srnyx** [comment]
> I've only been testing it on the client, so I sure hope it works on the client 😄

Wasn't Shut up Console made for servers? 😳

**Comment by wafflecoffee** [comment]
Maybe, but it still worked on the client either way.
